"""Initial migration

Revision ID: 850cd41b4e83
Revises: 9a97a61fe92b
Create Date: 2025-06-12 11:46:14.684826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850cd41b4e83'
down_revision: Union[str, None] = '9a97a61fe92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_table('todos')
    op.alter_column('contacts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_contacts_user_id_users'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contacts_user_id_users'), 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('contacts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('todos_pkey'))
    )
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    # ### end Alembic commands ###
